==16314== Memcheck, a memory error detector
==16314== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16314== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==16314== Command: ./test
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BB57: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11C028: Conjunto<int>::destructor() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11B7BB: Conjunto<int>::~Conjunto() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117255: conjunto_test_test_insertar_cinco_valores_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==  Address 0x4de76d8 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BB57: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11C028: Conjunto<int>::destructor() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11B7BB: Conjunto<int>::~Conjunto() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117255: conjunto_test_test_insertar_cinco_valores_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117121: conjunto_test_test_insertar_cinco_valores_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118409: conjunto_test_test_remover_caso_dos_hijos_raiz_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Address 0x4de9898 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118409: conjunto_test_test_remover_caso_dos_hijos_raiz_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118387: conjunto_test_test_remover_caso_dos_hijos_raiz_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11C028: Conjunto<int>::destructor() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11B7BB: Conjunto<int>::~Conjunto() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11874D: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==  Address 0x4dea078 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11C028: Conjunto<int>::destructor() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11B7BB: Conjunto<int>::~Conjunto() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11874D: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11864D: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11956F: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Address 0x4deab58 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11956F: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118F0E: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BB57: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1199B4: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Address 0x4df0d38 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BB57: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1199B4: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118F0E: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== Invalid read of size 8
==16314==    at 0x11C274: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1199B4: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Address 0x4df2ef8 is 24 bytes inside a block of size 32 free'd
==16314==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11C232: Conjunto<int>::transplant(Conjunto<int>::Nodo*, Conjunto<int>::Nodo*) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11BC51: Conjunto<int>::remover(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1199B4: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==  Block was alloc'd at
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118F0E: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 
==16314== HEAP SUMMARY:
==16314==     in use at exit: 32,096 bytes in 1,003 blocks
==16314==   total heap usage: 1,364 allocs, 361 frees, 160,235 bytes allocated
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 6 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11713B: conjunto_test_test_insertar_cinco_valores_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 7 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x11716F: conjunto_test_test_insertar_cinco_valores_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 8 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117BD1: conjunto_test_test_minimo_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 9 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117C05: conjunto_test_test_minimo_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 10 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117DC3: conjunto_test_test_maximo_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 11 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117DF7: conjunto_test_test_maximo_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 12 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x117FB5: conjunto_test_test_remover_caso_un_hijo_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 13 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118191: conjunto_test_test_remover_caso_dos_hijos_simple_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 14 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1183A1: conjunto_test_test_remover_caso_dos_hijos_raiz_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 15 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1185B1: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 16 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1185FF: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 32 bytes in 1 blocks are definitely lost in loss record 17 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118829: conjunto_test_test_siguiente_inorder_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 18 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1181AB: conjunto_test_test_remover_caso_dos_hijos_simple_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 19 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x1185CB: conjunto_test_test_remover_caso_dos_hijos_doble_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 20 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118877: conjunto_test_test_siguiente_inorder_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== 31,456 (5,568 direct, 25,888 indirect) bytes in 174 blocks are definitely lost in loss record 22 of 22
==16314==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16314==    by 0x11B8FA: Conjunto<int>::insertar(int const&) (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x118F0E: conjunto_test_test_stress_Test::TestBody() (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314==    by 0x14D390: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest.cc:2433)
==16314==    by 0x14D390: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x1406E5: Run (gtest.cc:2508)
==16314==    by 0x1406E5: testing::Test::Run() (gtest.cc:2498)
==16314==    by 0x140844: Run (gtest.cc:2684)
==16314==    by 0x140844: testing::TestInfo::Run() (gtest.cc:2657)
==16314==    by 0x14092C: Run (gtest.cc:2816)
==16314==    by 0x14092C: testing::TestSuite::Run() (gtest.cc:2795)
==16314==    by 0x140E4B: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5338)
==16314==    by 0x14D900: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest.cc:2433)
==16314==    by 0x14D900: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2469)
==16314==    by 0x14107B: testing::UnitTest::Run() (gtest.cc:4925)
==16314==    by 0x116CA3: main (in /home/algo2/algo2/algobot/algobot/2022-c2/repos/411_18/taller2/correcciones/2022-11-26/test)
==16314== 
==16314== LEAK SUMMARY:
==16314==    definitely lost: 6,048 bytes in 189 blocks
==16314==    indirectly lost: 26,048 bytes in 814 blocks
==16314==      possibly lost: 0 bytes in 0 blocks
==16314==    still reachable: 0 bytes in 0 blocks
==16314==         suppressed: 0 bytes in 0 blocks
==16314== 
==16314== For lists of detected and suppressed errors, rerun with: -s
==16314== ERROR SUMMARY: 51 errors from 22 contexts (suppressed: 0 from 0)
